apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: rahulpashikanti1999/rahulpashikanti:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app: myjavaapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: nodePort
